In [1]:
import scipy as sp
import io
import numpy as np

In [14]:
matrix4D= np.ones((4,4))
print(matrix4D)

fileObj=open("test.txt","w+")

for i in matrix4D:
    fileObj.write(str(i));
    
fileReadObj=open("test.txt","r")
if fileReadObj.mode == "r":
    contents=fileReadObj.read()
    print(contents)
   

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1.][1. 1. 1. 1.][1. 1. 1. 1.][1. 1. 1. 1.]


In [15]:
from scipy.special import cbrt
my_cb = cbrt([27,64,891])
print("The cube roots are :")
print(my_cb)

The cube roots are :
[3.         4.         9.62260299]


In [24]:
matrix2D1= np.array([[4,5],[3,2]])
matrix2D2= np.array([[4,5],[3,2]])

determinant=sp.linalg.det(matrix2D1)
print(determinant)

inverseMat= sp.linalg.inv(matrix2D2)
print(inverseMat)

-7.0
[[-0.28571429  0.71428571]
 [ 0.42857143 -0.57142857]]


In [25]:
matrix2D3= np.array([[5,4],[6,3]])
eigenVal=sp.linalg.eigh(matrix2D3)
print(eigenVal)

(array([-2.08276253, 10.08276253]), array([[ 0.6463749 , -0.76301998],
       [-0.76301998, -0.6463749 ]]))


In [29]:
from scipy.sparse import csr_matrix
arr = np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])

print(csr_matrix(arr))
print(csr_matrix(arr).data)
print(csr_matrix(arr).count_nonzero())

mat = csr_matrix(arr)
mat.eliminate_zeros()
print(mat)

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2
[1 1 2]
3
  (0, 5)	1
  (0, 6)	1
  (0, 8)	2
