In [1]:
import numpy as np

In [19]:
listNums=[]
userSize=int(input("Enter size of list:"))
for i in range(userSize):
    userEle=int(input("Enter element:"))
    listNums.append(userEle)
arr= np.array(listNums)
uniqueEle,frequency= np.unique(arr,return_counts= True)
print(uniqueEle)
print(frequency)

Enter size of list:5
Enter element:1
Enter element:2
Enter element:3
Enter element:1
Enter element:1
[1 2 3]
[3 1 1]


In [21]:
binaryList=[]
size=int(input("Enter size of list:"))
for i in range(size):
    ele=int(input(""))
    binaryList.append(ele)
arr=np.array(binaryList)
arr=np.sort(arr)
arr=arr[::-1]
print(arr)

Enter size of list:5
1
1
0
1
0
[1 1 1 0 0]


In [22]:
def remove_char(str, n):
      first_part = str[:n] 
      last_part = str[n+1:]
      return first_part + last_part
userChoice=int(input("Enter desired n:"))
userStr=input("Enter String:")
print(remove_char(userStr,userChoice))

Enter desired n:4
Enter String:Hello World
Hell World


In [25]:
listNums1=[]
userSize1=int(input("Enter size of list1:"))
for i in range(userSize1):
    userEle1=int(input("Enter element:"))
    listNums1.append(userEle1)
arr1= np.array(listNums1)

listNums2=[]
userSize2=int(input("Enter size of list2:"))
for i in range(userSize2):
    userEle2=int(input("Enter element:"))
    listNums2.append(userEle2)
arr2= np.array(listNums2)
   
print (np.in1d(arr1, arr2))


Enter size of list1:5
Enter element:1
Enter element:2
Enter element:3
Enter element:4
Enter element:5
Enter size of list2:5
Enter element:6
Enter element:7
Enter element:3
Enter element:2
Enter element:1
[ True  True  True False False]


In [26]:
listNums3=[]
userSize3=int(input("Enter size of list1:"))
for i in range(userSize3):
    userEle3=int(input("Enter element:"))
    listNums3.append(userEle3)
arr1= np.array(listNums3)

listNums4=[]
userSize4=int(input("Enter size of list2:"))
for i in range(userSize4):
    userEle4=int(input("Enter element:"))
    listNums4.append(userEle4)
arr2= np.array(listNums4)
   
print (np.setxor1d(arr1, arr2))


Enter size of list1:5
Enter element:3
Enter element:4
Enter element:2
Enter element:5
Enter element:1
Enter size of list2:5
Enter element:6
Enter element:5
Enter element:7
Enter element:3
Enter element:8
[1 2 4 6 7 8]
